### ISSUE TITLE
template command doesn't work

### ISSUE THREAD

**Issue by ez-krk** [solana-mobile/solana-mobile-dapp-scaffold#12]
tried to run the following : 
```bash
npx react-native init MyApp --template https://github.com/solana-mobile/solana-mobile-dapp-scaffold.git
```

got the following error : 
```
✖ Downloading template
error Command failed with exit code 1: yarn add https://github.com/solana-mobile/solana-mobile-dapp-scaffold.git
Usage Error: It seems you are trying to add a package using a https:... url; we now require package names to be explicitly specified.
Try running the command again with the package name prefixed: yarn add my-package@https:...
```

ain't much you can do on your side to solve this, since it seems related to react-native who didn't updated their methods.

still, we can't run the template command, docs needs a fix :<

or simply a template repo to fork would do ?

**Comment by Michaelsulistio** [comment]
@ez-krk hey, thanks for reporting and apologies for this! I'll investigate it more thoroughly tomorrow, but here's a couple of things to try now.

1. Its possible that you have an older/incompatible version of `react-native-cli`. Try following the [instructions](https://reactnative.dev/docs/0.69/typescript#getting-started-with-typescript) here.

```
If the above command is failing, you may have an old version of react-native or react-native-cli installed globally on your system. To fix the issue try uninstalling the CLI:
```

2. If you go into the `template/` folder, this is exactly what the template will be, but your project and app name will be `SolanaMobileDAppScaffold`. You'll have to manually refactor/change the names throughout the app (including the `android/` folders).

3. Tomorrow, I can upload this template as a package on npm, to fix the error complaining about the `https://` url.

Also, if could give some more info about your environment?

- `npx react-native -v` ?
- Windows/Mac/Linux?

**Comment by ez-krk** [comment]
```bash
npx react-native -v
11.3.5
```

arch linux.

**Comment by Michaelsulistio** [comment]
Fixed! This issue stems from compatibility issues with newer versions of `yarn` (namely yarn 3) that expect non-https dependencies. To remedy this I've published the repo as a package on npm.

You can install it now with this new command:
```
npx react-native init MySolanaDapp --template @solana-mobile/solana-mobile-dapp-scaffold --npm
```
